NumPy stands for Numerical Python.

Why do we use Numpy over normal list:

1. Faster operations.
2. It provides several mathematical operations.


In [3]:
#importing the numpy library
import numpy as np

Time taken- Numpy vs lists

In [4]:
from time import process_time

In [8]:
#time taken by list

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001318747000000009


In [9]:
#time taken by numpy array

np_array = np.array([i for i in range(10000)])

start_time = process_time()

# np_array = np_array + 5
np_array += 5 

end_time = process_time()

print (end_time - start_time)


0.0008968310000003754


In [10]:
# list

list = [1,2,3,4,5]
type(list)

list

In [11]:
# numpy array

numpy_array = np.array([1,2,3,4,5])
type(numpy_array)

numpy.ndarray

In [12]:
#creating a 1D array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
a.shape

(5,)

In [18]:
# creating a 2D array

a = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(a)



[[1 2 3 4 5]
 [2 3 4 5 6]]


In [62]:
y = np.ones((2, 3, 4))
print(y)
y.ndim

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


3

In [17]:
a.shape

(2, 5)

In [66]:
#intial placeholders in numpy array

#creating an array of zeros of given shape

x = np.zeros((5,5,6))
print(x)
print(x.ndim)
print(x.shape)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
3
(5, 5, 6)


In [21]:
x = np.zeros((5,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [23]:
#creating an array of ones

y = np.ones((5,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [25]:
#creating an identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
#creating a numpy array of a particular value

a = np.full((4,5),8)
print(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [29]:
#creating a numpy array of random numbers

a = np.random.random((4,5))
print(a)

[[0.24902943 0.08473323 0.19013283 0.25572257 0.80746175]
 [0.46419679 0.05885397 0.29943838 0.10819706 0.18956278]
 [0.89448611 0.90431495 0.49982305 0.60269197 0.22964372]
 [0.57612019 0.83515111 0.15375823 0.17809676 0.54019237]]


In [30]:
#creating a numpy array of some random integers
c = np.random.randint(10,50,(4,5))
print(c)

[[37 23 20 46 23]
 [44 36 34 10 49]
 [38 18 22 43 46]
 [41 48 18 15 32]]


In [31]:
#array of evenly spaced values

a = np.linspace(10,30,5)
print(a) 

[10. 15. 20. 25. 30.]


In [36]:
b = np.linspace(12,20, 5)
print(b)

[12. 14. 16. 18. 20.]


In [37]:
c = np.linspace(10,50, 7)
print(c)

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


In [39]:
#creating an array of numbers at a particular step

a = np.arange(10,30,5)

print(a)

[10 15 20 25]


In [40]:
b = np.arange(10,30,6)
print(b)

[10 16 22 28]


In [46]:
#converting a list into an numpy array

list2 = [2,3,4,5,6,7]

array = np.asarray(list2)
print(array)

[2 3 4 5 6 7]


In [47]:
type(array)

numpy.ndarray

In [48]:
type(list2)

list

In [51]:
#analysing a numpy array

a = np.random.randint(10,30,(5,6))
print(a)

[[18 24 23 18 21 26]
 [17 29 14 15 20 28]
 [19 20 21 23 27 15]
 [13 10 25 14 21 14]
 [21 16 20 16 10 15]]


In [53]:
#checking the shape of a 

a.shape

print(a.shape)

(5, 6)


In [54]:
#checking the number of dimensions in a given array

print(a.ndim)

2


In [56]:
a = np.array(([1,2,3],[3,4,5],[4,5,6]))
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [57]:
a.ndim

2

In [67]:
a.size

9

In [69]:
print(a.dtype)

int64


Mathematical operations in numpy array:


In [71]:
a = np.random.randint(10,20,(4,5))
b = np.random.randint(20,30,(4,5))
print(a)
print(b)

[[15 13 15 14 16]
 [10 12 15 10 18]
 [16 19 10 13 15]
 [15 19 19 17 14]]
[[22 24 25 24 22]
 [23 29 20 24 28]
 [29 29 20 24 23]
 [21 21 20 20 29]]


In [72]:
print(a+b)


[[37 37 40 38 38]
 [33 41 35 34 46]
 [45 48 30 37 38]
 [36 40 39 37 43]]


In [73]:
print(a*b)

[[330 312 375 336 352]
 [230 348 300 240 504]
 [464 551 200 312 345]
 [315 399 380 340 406]]


In [74]:
print(a/b)

[[0.68181818 0.54166667 0.6        0.58333333 0.72727273]
 [0.43478261 0.4137931  0.75       0.41666667 0.64285714]
 [0.55172414 0.65517241 0.5        0.54166667 0.65217391]
 [0.71428571 0.9047619  0.95       0.85       0.48275862]]


In [75]:
print(a-b)

[[ -7 -11 -10 -10  -6]
 [-13 -17  -5 -14 -10]
 [-13 -10 -10 -11  -8]
 [ -6  -2  -1  -3 -15]]


In [76]:
c = np.random.randint(5,10,(4,4))
d = np.random.randint(10,15,(4,4))
print(c)
print(d)

[[7 5 8 5]
 [9 8 8 7]
 [8 9 9 5]
 [8 8 7 5]]
[[10 12 14 13]
 [11 11 11 12]
 [14 11 11 14]
 [14 13 14 14]]


In [77]:
print(np.add(c,d))


[[17 17 22 18]
 [20 19 19 19]
 [22 20 20 19]
 [22 21 21 19]]


In [78]:
print(np.multiply(c,d))

[[ 70  60 112  65]
 [ 99  88  88  84]
 [112  99  99  70]
 [112 104  98  70]]


In [79]:
print(np.subtract(c,d))

[[-3 -7 -6 -8]
 [-2 -3 -3 -5]
 [-6 -2 -2 -9]
 [-6 -5 -7 -9]]


In [80]:
print(np.divide(c,d))

[[0.7        0.41666667 0.57142857 0.38461538]
 [0.81818182 0.72727273 0.72727273 0.58333333]
 [0.57142857 0.81818182 0.81818182 0.35714286]
 [0.57142857 0.61538462 0.5        0.35714286]]


In [84]:
array = np.random.randint(10,20,(5,6))
print(array)
array.shape

[[19 17 16 19 16 15]
 [12 13 16 13 17 14]
 [18 10 12 17 18 17]
 [12 19 19 17 13 10]
 [11 12 13 16 11 18]]


(5, 6)

In [85]:
trans = np.transpose(array)
print(trans)
trans.shape

[[19 12 18 12 11]
 [17 13 10 19 12]
 [16 16 12 19 13]
 [19 13 17 17 16]
 [16 17 18 13 11]
 [15 14 17 10 18]]


(6, 5)

In [86]:
array1 = np.random.randint(20,50,(6,7))
print(array1)

[[30 37 34 33 30 32 39]
 [24 39 25 48 21 48 43]
 [30 42 29 48 26 33 46]
 [21 20 25 38 40 20 25]
 [24 30 34 41 38 32 29]
 [20 26 24 23 20 27 22]]


In [88]:
array2 = array1.reshape(7,6)
print(array2)

[[30 37 34 33 30 32]
 [39 24 39 25 48 21]
 [48 43 30 42 29 48]
 [26 33 46 21 20 25]
 [38 40 20 25 24 30]
 [34 41 38 32 29 20]
 [26 24 23 20 27 22]]
